<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jimx.WebAggregator.Browser\Jimx.WebAggregator.Browser.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Domain.CityCosts\Jimx.WebAggregator.Domain.CityCosts.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Domain.JobNet\Jimx.WebAggregator.Domain.JobNet.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Parser.Html.LifeLevel\Jimx.WebAggregator.Parser.Html.LifeLevel.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Parser.Html\Jimx.WebAggregator.Parser.Html.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Parser\Jimx.WebAggregator.Parser.csproj" />
    <ProjectReference Include="..\Jimx.WebAggregator.Persistent.MongoDB\Jimx.WebAggregator.Persistent.MongoDB.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExtensionRequests\" />
  </ItemGroup>

</Project>
