<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0"/>
        <PackageReference Include="NUnit" Version="4.3.2"/>
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Jimx.WebAggregator.Parser.Html.LifeLevel\Jimx.WebAggregator.Parser.Html.LifeLevel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="ExtractorTestFiles\test1.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test1.html" />
      <None Remove="ExtractorTestFiles\test2.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test2.html" />
      <None Remove="ExtractorTestFiles\test3.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test3.html" />
      <None Remove="ExtractorTestFiles\test6.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test6.html" />
      <None Remove="ExtractorTestFiles\test5.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test5.html" />
      <None Remove="ExtractorTestFiles\test4.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test4.html" />
      <None Remove="ExtractorTestFiles\test7.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test7.html" />
      <None Remove="ExtractorTestFiles\test9.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test9.html" />
      <None Remove="ExtractorTestFiles\test8.html" />
      <EmbeddedResource Include="ExtractorTestFiles\test8.html" />
    </ItemGroup>

</Project>
